[package]
name = "btcusd_protocol"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.9.2"

[dependencies]
starknet = "2.9.2"
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.20.0" }
openzeppelin_access = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.20.0" }
openzeppelin_security = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.20.0" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.35.1" }

[[target.starknet-contract]]
sierra = true
casm = true

[tool.snforge]
