[package]
name = "btcusd_protocol"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.9.2"

[dependencies]
starknet = "2.9.2"
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.20.0" }
openzeppelin_access = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.20.0" }
openzeppelin_security = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.20.0" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git", tag = "v0.3.0" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.35.1" }

[[target.starknet-contract]]
sierra = true
casm = true

[[test]]
name = "btcusd_protocol_integrationtest"
build-external-contracts = ["btcusd_protocol::*"]

[scripts]
test = "snforge test"

[tool.snforge]
exit_first = false
