[sncast.default]
url = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_7/demo"

[sncast.deployer]
url = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_7/demo"
account = "deployer"
accounts-file = "../.starkli-wallets/deployer/account.json"
keystore = "../.starkli-wallets/deployer/keystore.json"
